// AUTO-GENERATED by scripts/update-visa-data.mjs — 수동 편집 금지.
// 수동 보강은 visaRequirements.ts 에서 관리.
// 출처: 공공데이터포털 - 외교부_국가·지역별 입국허가요건 (dataset 15076574)
// Fetched at: 2026-04-15T08:02:26.904Z

export interface VisaRequirement {
  /** 일반여권 기준 비자 필요 여부. null = 판정 불가 */
  required: boolean | null;
  /** 무사증 체류 가능 일수. null = 해당 없음 */
  stayDays: number | null;
  /** 외교부 원문(일반여권소지자 - 입국가능기간) */
  rawText: string;
  /** 비고 또는 무비자 입국 근거 (일반여권 부분만) */
  note: string | null;
}

export const GENERATED_VISA_REQUIREMENTS: Record<string, VisaRequirement> = {
  AM: { required: false, stayDays: 180, rawText: "180일", note: null },
  AZ: { required: true, stayDays: null, rawText: "X", note: null },
  CN: {
    required: true,
    stayDays: null,
    rawText: "하이난 지역 - 일반 여권 소지자 무사증 입국 가능",
    note: "체류기간 최장30일, 현지 전담 여행사 통하여 입국 최소 48시간전 신청필요",
  },
  EG: { required: true, stayDays: null, rawText: "X", note: null },
  ES: { required: false, stayDays: 90, rawText: "90일", note: null },
  GB: { required: false, stayDays: 180, rawText: "6개월", note: null },
  GE: { required: false, stayDays: 365, rawText: "365일, 일방", note: null },
  GR: { required: false, stayDays: 90, rawText: "90일", note: null },
  HR: { required: false, stayDays: 90, rawText: "90일", note: null },
  ID: { required: true, stayDays: null, rawText: "X", note: null },
  IN: { required: true, stayDays: null, rawText: "X", note: null },
  IR: { required: true, stayDays: null, rawText: "X", note: null },
  JP: { required: false, stayDays: 90, rawText: "90일", note: null },
  KG: {
    required: false,
    stayDays: 60,
    rawText: "60일",
    note: "관광목적, 일방적 면제",
  },
  KH: { required: true, stayDays: null, rawText: "X", note: null },
  KZ: {
    required: false,
    stayDays: 30,
    rawText: "30일",
    note: "* 최초 입국일 기준 180일 중 60일 초과 불가",
  },
  LA: { required: false, stayDays: 30, rawText: "30일", note: null },
  LK: { required: true, stayDays: null, rawText: "X", note: null },
  MA: { required: false, stayDays: 90, rawText: "90일", note: null },
  MN: {
    required: true,
    stayDays: null,
    rawText: "관광목적 90일 비자면제",
    note: "일방 (~24년12월31일까지)",
  },
  MO: { required: false, stayDays: 90, rawText: "90일", note: null },
  MV: { required: true, stayDays: null, rawText: "X", note: null },
  MY: { required: false, stayDays: 90, rawText: "90일", note: null },
  NP: { required: true, stayDays: null, rawText: "X", note: null },
  NZ: { required: false, stayDays: 90, rawText: "90일", note: null },
  PH: { required: false, stayDays: 30, rawText: "30일", note: null },
  PT: { required: true, stayDays: null, rawText: "180일 중 90일", note: null },
  RU: {
    required: true,
    stayDays: null,
    rawText: "60일 180일 이내 총 90일 초과 불가, 1회 연속체류 최대 60일",
    note: null,
  },
  SG: { required: false, stayDays: 90, rawText: "90일", note: null },
  SI: { required: false, stayDays: 90, rawText: "90일", note: null },
  SY: { required: true, stayDays: null, rawText: "X", note: null },
  TH: { required: false, stayDays: 90, rawText: "90일", note: null },
  TR: { required: true, stayDays: null, rawText: "180일 중 90일", note: null },
  TW: { required: false, stayDays: 90, rawText: "90일", note: null },
  US: { required: false, stayDays: 90, rawText: "90일", note: null },
  UZ: { required: false, stayDays: 30, rawText: "30일", note: null },
  VN: { required: false, stayDays: 45, rawText: "45일", note: null },
};

export const VISA_DATA_FETCHED_AT = "2026-04-15T08:02:26.904Z";
