import {
  Plane,
  Smartphone,
  Shirt,
  Droplet,
  Sparkles,
  Pill,
  Package,
  Baby,
  Dog,
  Dumbbell,
  Waves,
  UtensilsCrossed,
  Briefcase,
  Camera,
  TreePine,
  Zap,
  Umbrella,
  Landmark,
  ShoppingBag,
  Sun,
  Snowflake,
  CloudRain,
  type LucideIcon,
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  "필수 준비물": Plane,
  전자제품: Smartphone,
  의류: Shirt,
  세면용품: Droplet,
  화장품: Sparkles,
  상비약: Pill,
  기타용품: Package,
  유아용품: Baby,
  반려동물용품: Dog,
  운동: Dumbbell,
  수영: Waves,
  한식: UtensilsCrossed,
  출장: Briefcase,
  관광: Camera,
  자연: TreePine,
  액티비티: Zap,
  휴양: Umbrella,
  문화: Landmark,
  쇼핑: ShoppingBag,
  미식: UtensilsCrossed,
  "여름 준비물": Sun,
  "겨울 준비물": Snowflake,
  "우기/장마 대비": CloudRain,
};
