/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PackingRouteImport } from './routes/packing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackingCreateRouteImport } from './routes/packing.create'

const PackingRoute = PackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackingCreateRoute = PackingCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => PackingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/packing': typeof PackingRouteWithChildren
  '/packing/create': typeof PackingCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/packing': typeof PackingRouteWithChildren
  '/packing/create': typeof PackingCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/packing': typeof PackingRouteWithChildren
  '/packing/create': typeof PackingCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/packing' | '/packing/create'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/packing' | '/packing/create'
  id: '__root__' | '/' | '/packing' | '/packing/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PackingRoute: typeof PackingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/packing': {
      id: '/packing'
      path: '/packing'
      fullPath: '/packing'
      preLoaderRoute: typeof PackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packing/create': {
      id: '/packing/create'
      path: '/create'
      fullPath: '/packing/create'
      preLoaderRoute: typeof PackingCreateRouteImport
      parentRoute: typeof PackingRoute
    }
  }
}

interface PackingRouteChildren {
  PackingCreateRoute: typeof PackingCreateRoute
}

const PackingRouteChildren: PackingRouteChildren = {
  PackingCreateRoute: PackingCreateRoute,
}

const PackingRouteWithChildren =
  PackingRoute._addFileChildren(PackingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PackingRoute: PackingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
