/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/main'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MypageIndexRouteImport } from './routes/mypage/index'
import { Route as ScheduleTripIdRouteImport } from './routes/schedule.$tripId'
import { Route as PackingTemplateRouteImport } from './routes/packing.template'
import { Route as PackingCreateRouteImport } from './routes/packing.create'
import { Route as MypagePastTripsRouteImport } from './routes/mypage/past-trips'
import { Route as InviteInviteCodeRouteImport } from './routes/invite.$inviteCode'
import { Route as ExpenseTripIdRouteImport } from './routes/expense.$tripId'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as MypageMyChecklistsIndexRouteImport } from './routes/mypage/my-checklists/index'
import { Route as TodoListTripIdRouteImport } from './routes/todo.list.$tripId'
import { Route as TodoCategoryTripIdRouteImport } from './routes/todo.category.$tripId'
import { Route as ShoppingListTripIdRouteImport } from './routes/shopping.list.$tripId'
import { Route as ShoppingCategoryTripIdRouteImport } from './routes/shopping.category.$tripId'
import { Route as PackingListTripIdRouteImport } from './routes/packing.list.$tripId'
import { Route as PackingCategoryTripIdRouteImport } from './routes/packing.category.$tripId'
import { Route as MypageMyChecklistsTemplateIdRouteImport } from './routes/mypage/my-checklists/$templateId'
import { Route as ExpenseSettlementTripIdRouteImport } from './routes/expense.settlement.$tripId'
import { Route as ScheduleEditTripIdDayNumberRouteImport } from './routes/schedule.edit.$tripId.$dayNumber'

const MainRoute = MainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageIndexRoute = MypageIndexRouteImport.update({
  id: '/mypage/',
  path: '/mypage/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleTripIdRoute = ScheduleTripIdRouteImport.update({
  id: '/schedule/$tripId',
  path: '/schedule/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const PackingTemplateRoute = PackingTemplateRouteImport.update({
  id: '/packing/template',
  path: '/packing/template',
  getParentRoute: () => rootRouteImport,
} as any)
const PackingCreateRoute = PackingCreateRouteImport.update({
  id: '/packing/create',
  path: '/packing/create',
  getParentRoute: () => rootRouteImport,
} as any)
const MypagePastTripsRoute = MypagePastTripsRouteImport.update({
  id: '/mypage/past-trips',
  path: '/mypage/past-trips',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteInviteCodeRoute = InviteInviteCodeRouteImport.update({
  id: '/invite/$inviteCode',
  path: '/invite/$inviteCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseTripIdRoute = ExpenseTripIdRouteImport.update({
  id: '/expense/$tripId',
  path: '/expense/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageMyChecklistsIndexRoute = MypageMyChecklistsIndexRouteImport.update({
  id: '/mypage/my-checklists/',
  path: '/mypage/my-checklists/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoListTripIdRoute = TodoListTripIdRouteImport.update({
  id: '/todo/list/$tripId',
  path: '/todo/list/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoCategoryTripIdRoute = TodoCategoryTripIdRouteImport.update({
  id: '/todo/category/$tripId',
  path: '/todo/category/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingListTripIdRoute = ShoppingListTripIdRouteImport.update({
  id: '/shopping/list/$tripId',
  path: '/shopping/list/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingCategoryTripIdRoute = ShoppingCategoryTripIdRouteImport.update({
  id: '/shopping/category/$tripId',
  path: '/shopping/category/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const PackingListTripIdRoute = PackingListTripIdRouteImport.update({
  id: '/packing/list/$tripId',
  path: '/packing/list/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const PackingCategoryTripIdRoute = PackingCategoryTripIdRouteImport.update({
  id: '/packing/category/$tripId',
  path: '/packing/category/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageMyChecklistsTemplateIdRoute =
  MypageMyChecklistsTemplateIdRouteImport.update({
    id: '/mypage/my-checklists/$templateId',
    path: '/mypage/my-checklists/$templateId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExpenseSettlementTripIdRoute = ExpenseSettlementTripIdRouteImport.update({
  id: '/expense/settlement/$tripId',
  path: '/expense/settlement/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleEditTripIdDayNumberRoute =
  ScheduleEditTripIdDayNumberRouteImport.update({
    id: '/schedule/edit/$tripId/$dayNumber',
    path: '/schedule/edit/$tripId/$dayNumber',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/main': typeof MainRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/expense/$tripId': typeof ExpenseTripIdRoute
  '/invite/$inviteCode': typeof InviteInviteCodeRoute
  '/mypage/past-trips': typeof MypagePastTripsRoute
  '/packing/create': typeof PackingCreateRoute
  '/packing/template': typeof PackingTemplateRoute
  '/schedule/$tripId': typeof ScheduleTripIdRoute
  '/mypage': typeof MypageIndexRoute
  '/expense/settlement/$tripId': typeof ExpenseSettlementTripIdRoute
  '/mypage/my-checklists/$templateId': typeof MypageMyChecklistsTemplateIdRoute
  '/packing/category/$tripId': typeof PackingCategoryTripIdRoute
  '/packing/list/$tripId': typeof PackingListTripIdRoute
  '/shopping/category/$tripId': typeof ShoppingCategoryTripIdRoute
  '/shopping/list/$tripId': typeof ShoppingListTripIdRoute
  '/todo/category/$tripId': typeof TodoCategoryTripIdRoute
  '/todo/list/$tripId': typeof TodoListTripIdRoute
  '/mypage/my-checklists': typeof MypageMyChecklistsIndexRoute
  '/schedule/edit/$tripId/$dayNumber': typeof ScheduleEditTripIdDayNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/main': typeof MainRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/expense/$tripId': typeof ExpenseTripIdRoute
  '/invite/$inviteCode': typeof InviteInviteCodeRoute
  '/mypage/past-trips': typeof MypagePastTripsRoute
  '/packing/create': typeof PackingCreateRoute
  '/packing/template': typeof PackingTemplateRoute
  '/schedule/$tripId': typeof ScheduleTripIdRoute
  '/mypage': typeof MypageIndexRoute
  '/expense/settlement/$tripId': typeof ExpenseSettlementTripIdRoute
  '/mypage/my-checklists/$templateId': typeof MypageMyChecklistsTemplateIdRoute
  '/packing/category/$tripId': typeof PackingCategoryTripIdRoute
  '/packing/list/$tripId': typeof PackingListTripIdRoute
  '/shopping/category/$tripId': typeof ShoppingCategoryTripIdRoute
  '/shopping/list/$tripId': typeof ShoppingListTripIdRoute
  '/todo/category/$tripId': typeof TodoCategoryTripIdRoute
  '/todo/list/$tripId': typeof TodoListTripIdRoute
  '/mypage/my-checklists': typeof MypageMyChecklistsIndexRoute
  '/schedule/edit/$tripId/$dayNumber': typeof ScheduleEditTripIdDayNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/main': typeof MainRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/expense/$tripId': typeof ExpenseTripIdRoute
  '/invite/$inviteCode': typeof InviteInviteCodeRoute
  '/mypage/past-trips': typeof MypagePastTripsRoute
  '/packing/create': typeof PackingCreateRoute
  '/packing/template': typeof PackingTemplateRoute
  '/schedule/$tripId': typeof ScheduleTripIdRoute
  '/mypage/': typeof MypageIndexRoute
  '/expense/settlement/$tripId': typeof ExpenseSettlementTripIdRoute
  '/mypage/my-checklists/$templateId': typeof MypageMyChecklistsTemplateIdRoute
  '/packing/category/$tripId': typeof PackingCategoryTripIdRoute
  '/packing/list/$tripId': typeof PackingListTripIdRoute
  '/shopping/category/$tripId': typeof ShoppingCategoryTripIdRoute
  '/shopping/list/$tripId': typeof ShoppingListTripIdRoute
  '/todo/category/$tripId': typeof TodoCategoryTripIdRoute
  '/todo/list/$tripId': typeof TodoListTripIdRoute
  '/mypage/my-checklists/': typeof MypageMyChecklistsIndexRoute
  '/schedule/edit/$tripId/$dayNumber': typeof ScheduleEditTripIdDayNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/main'
    | '/auth/login'
    | '/auth/signup'
    | '/expense/$tripId'
    | '/invite/$inviteCode'
    | '/mypage/past-trips'
    | '/packing/create'
    | '/packing/template'
    | '/schedule/$tripId'
    | '/mypage'
    | '/expense/settlement/$tripId'
    | '/mypage/my-checklists/$templateId'
    | '/packing/category/$tripId'
    | '/packing/list/$tripId'
    | '/shopping/category/$tripId'
    | '/shopping/list/$tripId'
    | '/todo/category/$tripId'
    | '/todo/list/$tripId'
    | '/mypage/my-checklists'
    | '/schedule/edit/$tripId/$dayNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/main'
    | '/auth/login'
    | '/auth/signup'
    | '/expense/$tripId'
    | '/invite/$inviteCode'
    | '/mypage/past-trips'
    | '/packing/create'
    | '/packing/template'
    | '/schedule/$tripId'
    | '/mypage'
    | '/expense/settlement/$tripId'
    | '/mypage/my-checklists/$templateId'
    | '/packing/category/$tripId'
    | '/packing/list/$tripId'
    | '/shopping/category/$tripId'
    | '/shopping/list/$tripId'
    | '/todo/category/$tripId'
    | '/todo/list/$tripId'
    | '/mypage/my-checklists'
    | '/schedule/edit/$tripId/$dayNumber'
  id:
    | '__root__'
    | '/'
    | '/main'
    | '/auth/login'
    | '/auth/signup'
    | '/expense/$tripId'
    | '/invite/$inviteCode'
    | '/mypage/past-trips'
    | '/packing/create'
    | '/packing/template'
    | '/schedule/$tripId'
    | '/mypage/'
    | '/expense/settlement/$tripId'
    | '/mypage/my-checklists/$templateId'
    | '/packing/category/$tripId'
    | '/packing/list/$tripId'
    | '/shopping/category/$tripId'
    | '/shopping/list/$tripId'
    | '/todo/category/$tripId'
    | '/todo/list/$tripId'
    | '/mypage/my-checklists/'
    | '/schedule/edit/$tripId/$dayNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRoute: typeof MainRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ExpenseTripIdRoute: typeof ExpenseTripIdRoute
  InviteInviteCodeRoute: typeof InviteInviteCodeRoute
  MypagePastTripsRoute: typeof MypagePastTripsRoute
  PackingCreateRoute: typeof PackingCreateRoute
  PackingTemplateRoute: typeof PackingTemplateRoute
  ScheduleTripIdRoute: typeof ScheduleTripIdRoute
  MypageIndexRoute: typeof MypageIndexRoute
  ExpenseSettlementTripIdRoute: typeof ExpenseSettlementTripIdRoute
  MypageMyChecklistsTemplateIdRoute: typeof MypageMyChecklistsTemplateIdRoute
  PackingCategoryTripIdRoute: typeof PackingCategoryTripIdRoute
  PackingListTripIdRoute: typeof PackingListTripIdRoute
  ShoppingCategoryTripIdRoute: typeof ShoppingCategoryTripIdRoute
  ShoppingListTripIdRoute: typeof ShoppingListTripIdRoute
  TodoCategoryTripIdRoute: typeof TodoCategoryTripIdRoute
  TodoListTripIdRoute: typeof TodoListTripIdRoute
  MypageMyChecklistsIndexRoute: typeof MypageMyChecklistsIndexRoute
  ScheduleEditTripIdDayNumberRoute: typeof ScheduleEditTripIdDayNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage/': {
      id: '/mypage/'
      path: '/mypage'
      fullPath: '/mypage'
      preLoaderRoute: typeof MypageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/$tripId': {
      id: '/schedule/$tripId'
      path: '/schedule/$tripId'
      fullPath: '/schedule/$tripId'
      preLoaderRoute: typeof ScheduleTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packing/template': {
      id: '/packing/template'
      path: '/packing/template'
      fullPath: '/packing/template'
      preLoaderRoute: typeof PackingTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packing/create': {
      id: '/packing/create'
      path: '/packing/create'
      fullPath: '/packing/create'
      preLoaderRoute: typeof PackingCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage/past-trips': {
      id: '/mypage/past-trips'
      path: '/mypage/past-trips'
      fullPath: '/mypage/past-trips'
      preLoaderRoute: typeof MypagePastTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$inviteCode': {
      id: '/invite/$inviteCode'
      path: '/invite/$inviteCode'
      fullPath: '/invite/$inviteCode'
      preLoaderRoute: typeof InviteInviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense/$tripId': {
      id: '/expense/$tripId'
      path: '/expense/$tripId'
      fullPath: '/expense/$tripId'
      preLoaderRoute: typeof ExpenseTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage/my-checklists/': {
      id: '/mypage/my-checklists/'
      path: '/mypage/my-checklists'
      fullPath: '/mypage/my-checklists'
      preLoaderRoute: typeof MypageMyChecklistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo/list/$tripId': {
      id: '/todo/list/$tripId'
      path: '/todo/list/$tripId'
      fullPath: '/todo/list/$tripId'
      preLoaderRoute: typeof TodoListTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo/category/$tripId': {
      id: '/todo/category/$tripId'
      path: '/todo/category/$tripId'
      fullPath: '/todo/category/$tripId'
      preLoaderRoute: typeof TodoCategoryTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping/list/$tripId': {
      id: '/shopping/list/$tripId'
      path: '/shopping/list/$tripId'
      fullPath: '/shopping/list/$tripId'
      preLoaderRoute: typeof ShoppingListTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping/category/$tripId': {
      id: '/shopping/category/$tripId'
      path: '/shopping/category/$tripId'
      fullPath: '/shopping/category/$tripId'
      preLoaderRoute: typeof ShoppingCategoryTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packing/list/$tripId': {
      id: '/packing/list/$tripId'
      path: '/packing/list/$tripId'
      fullPath: '/packing/list/$tripId'
      preLoaderRoute: typeof PackingListTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packing/category/$tripId': {
      id: '/packing/category/$tripId'
      path: '/packing/category/$tripId'
      fullPath: '/packing/category/$tripId'
      preLoaderRoute: typeof PackingCategoryTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage/my-checklists/$templateId': {
      id: '/mypage/my-checklists/$templateId'
      path: '/mypage/my-checklists/$templateId'
      fullPath: '/mypage/my-checklists/$templateId'
      preLoaderRoute: typeof MypageMyChecklistsTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense/settlement/$tripId': {
      id: '/expense/settlement/$tripId'
      path: '/expense/settlement/$tripId'
      fullPath: '/expense/settlement/$tripId'
      preLoaderRoute: typeof ExpenseSettlementTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/edit/$tripId/$dayNumber': {
      id: '/schedule/edit/$tripId/$dayNumber'
      path: '/schedule/edit/$tripId/$dayNumber'
      fullPath: '/schedule/edit/$tripId/$dayNumber'
      preLoaderRoute: typeof ScheduleEditTripIdDayNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRoute: MainRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  ExpenseTripIdRoute: ExpenseTripIdRoute,
  InviteInviteCodeRoute: InviteInviteCodeRoute,
  MypagePastTripsRoute: MypagePastTripsRoute,
  PackingCreateRoute: PackingCreateRoute,
  PackingTemplateRoute: PackingTemplateRoute,
  ScheduleTripIdRoute: ScheduleTripIdRoute,
  MypageIndexRoute: MypageIndexRoute,
  ExpenseSettlementTripIdRoute: ExpenseSettlementTripIdRoute,
  MypageMyChecklistsTemplateIdRoute: MypageMyChecklistsTemplateIdRoute,
  PackingCategoryTripIdRoute: PackingCategoryTripIdRoute,
  PackingListTripIdRoute: PackingListTripIdRoute,
  ShoppingCategoryTripIdRoute: ShoppingCategoryTripIdRoute,
  ShoppingListTripIdRoute: ShoppingListTripIdRoute,
  TodoCategoryTripIdRoute: TodoCategoryTripIdRoute,
  TodoListTripIdRoute: TodoListTripIdRoute,
  MypageMyChecklistsIndexRoute: MypageMyChecklistsIndexRoute,
  ScheduleEditTripIdDayNumberRoute: ScheduleEditTripIdDayNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
